describe('buyed like a costumer and logout', () => {
    it('user buying many elements', () => { 
      cy.login ({username:'thisisafalseuser',password:'thisisfalsepassword'})
      cy.get('a[id="itemc"]').contains('Phones').click({force: true})
      cy.get('a').contains('Samsung galaxy s6').click({force: true})
      cy.get('a[class="btn btn-success btn-lg"]').click()
      cy.get('a').contains('Home').click()
      cy.get('a[class="hrefch"]').contains('Iphone 6 32gb').click()
      cy.get('a[class="btn btn-success btn-lg"]').click()
      cy.get('a[id="nava"]').click()
      cy.get('a[id="itemc"]').contains('Laptops').click()
      cy.get('a[class="hrefch"]').contains('2017 Dell 15.6 Inch').click()
      cy.get('a[class="btn btn-success btn-lg"]').click()
      cy.go('back')
      cy.go('back')
      cy.get('a[class="hrefch"]').contains('Sony vaio i7').click()
      cy.get('a[class="btn btn-success btn-lg"]').click()
      cy.get('a[id="nava"]').click()
      cy.get('a[id="itemc"]').contains('Monitors').click()
      cy.get('a[href="prod.html?idp_=10"]').contains('Apple monitor 24').click()
      cy.get('a[class="btn btn-success btn-lg"]').click()
      cy.get('a').contains('Home').click()
      cy.get('a[id="itemc"]').contains('Monitors').click()
      cy.get('a[class="hrefch"]').contains('ASUS Full HD').click()
      cy.get('a[class="btn btn-success btn-lg"]').click()
      cy.get('a').contains('Cart').click()
      cy.get('button').contains('Place Order').click()
      cy.get('input[id="name"]').type('Jefferson Gutierritos')
      cy.get('input[id="country"]').type('Locombia')
      cy.get('input[id="city"]').type('Chochó')
      cy.get('input[id="card"]').type('5573367061899851')
      cy.get('input[id="month"]').type('12')
      cy.get('input[id="year"]').type('2021')
      cy.get('button').contains('Purchase').click()
      cy.get('button').contains('OK').click()
      cy.get('a[id="logout2"]').click({force: true})
    })
})